using System;
namespace MiGameGeneral{
	class linkerController{
		public linkerController(){
		}
		public void toString(){
		}
		public void linkFunction(){
			var obj0 = new MiruGameScript();
			obj0.linkFunction();
			var obj1 = new MiruAdmin();
			obj1.linkFunction();
			var obj2 = new MiruBattle();
			obj2.linkFunction();
			var obj3 = new MiruAI();
			obj3.linkFunction();
			var obj4 = new MiruBuf();
			obj4.linkFunction();
			var obj5 = new MiruMagicEffect();
			obj5.linkFunction();
			var obj6 = new MiruRole();
			obj6.linkFunction();
			var obj7 = new MiruAction();
			obj7.linkFunction();
			var obj8 = new MiruDT();
			obj8.linkFunction();
			var obj9 = new MiruData();
			obj9.linkFunction();
			var obj10 = new MiruGoodsDT();
			obj10.linkFunction();
			var obj11 = new MiruPoolDT();
			obj11.linkFunction();
			var obj12 = new MiruCardBattle();
			obj12.linkFunction();
			var obj13 = new MiruCardSubpoolDt();
			obj13.linkFunction();
			var obj14 = new MiruPatrol();
			obj14.linkFunction();
			var obj15 = new MiruRankList();
			obj15.linkFunction();
			var obj16 = new MiruScDT();
			obj16.linkFunction();
			var obj17 = new MiruGameEM();
			obj17.linkFunction();
			var obj18 = new MiruGloData();
			obj18.linkFunction();
			var obj19 = new MiruGuidance();
			obj19.linkFunction();
			var obj20 = new MiruInvalidScripts();
			obj20.linkFunction();
			var obj21 = new MiruInvalidScripts01();
			obj21.linkFunction();
			var obj22 = new MiruLanguageSet();
			obj22.linkFunction();
			var obj23 = new MiruLegionSystem();
			obj23.linkFunction();
			var obj24 = new MiruPool();
			obj24.linkFunction();
			var obj25 = new MiruSC();
			obj25.linkFunction();
			var obj26 = new MiruUI();
			obj26.linkFunction();
			var obj27 = new MiruHallSubPage();
			obj27.linkFunction();
			var obj28 = new MiruItem();
			obj28.linkFunction();
			var obj29 = new MiruLegionBattle();
			obj29.linkFunction();
			var obj30 = new MiruLegionDungeon();
			obj30.linkFunction();
			var obj31 = new MiruLog();
			obj31.linkFunction();
			var obj32 = new MiruMemoryProfiler();
			obj32.linkFunction();
			var obj37 = new MiruMessage();
			obj37.linkFunction();
			var obj38 = new MiruPlot();
			obj38.linkFunction();
			var obj39 = new MiruIconData();
			obj39.linkFunction();
			var obj40 = new MiruLocalPool();
			obj40.linkFunction();
			var obj41 = new MiruPlayerPool();
			obj41.linkFunction();
			var obj42 = new MiruUserData();
			obj42.linkFunction();
			var obj43 = new MiruResourceManager();
			obj43.linkFunction();
			var obj44 = new MiruResManager();
			obj44.linkFunction();
			var obj45 = new MiruSDKComponent();
			obj45.linkFunction();
			var obj46 = new MiruNoChannelSDK();
			obj46.linkFunction();
			var obj49 = new MiruSocket();
			obj49.linkFunction();
			var obj50 = new MiruSocketDT();
			obj50.linkFunction();
			var obj51 = new MiruSocketState();
			obj51.linkFunction();
			var obj52 = new MiruSound();
			obj52.linkFunction();
			var obj53 = new MiruTools();
			obj53.linkFunction();
			var obj54 = new MiruCmd();
			obj54.linkFunction();
			var obj55 = new MiruAward();
			obj55.linkFunction();
			var obj56 = new MiruBag();
			obj56.linkFunction();
			var obj57 = new MiruBattleFormPage();
			obj57.linkFunction();
			var obj58 = new MiruBattleScene();
			obj58.linkFunction();
			var obj59 = new MiruCardMenu();
			obj59.linkFunction();
			var obj60 = new MiruCardProperty();
			obj60.linkFunction();
			var obj61 = new MiruCardShow();
			obj61.linkFunction();
			var obj62 = new MiruChatmanage();
			obj62.linkFunction();
			var obj63 = new MiruCommon();
			obj63.linkFunction();
			var obj64 = new MiruDialog();
			obj64.linkFunction();
			var obj65 = new MiruTip();
			obj65.linkFunction();
			var obj66 = new MiruWrapUI();
			obj66.linkFunction();
			var obj67 = new MiruEmojiManage();
			obj67.linkFunction();
			var obj68 = new MiruEquipManage();
			obj68.linkFunction();
			var obj69 = new MiruFateTrip();
			obj69.linkFunction();
			var obj70 = new MiruGainCardShow();
			obj70.linkFunction();
			var obj71 = new MiruGameMain();
			obj71.linkFunction();
			var obj72 = new MiruActivity();
			obj72.linkFunction();
			var obj73 = new MiruBuildMenu();
			obj73.linkFunction();
			var obj74 = new MiruBuildPage();
			obj74.linkFunction();
			var obj75 = new MiruCardChange();
			obj75.linkFunction();
			var obj76 = new MiruChallenge();
			obj76.linkFunction();
			var obj77 = new MiruArena();
			obj77.linkFunction();
			var obj78 = new MiruCrossServerBattle();
			obj78.linkFunction();
			var obj79 = new MiruGrabTreasure();
			obj79.linkFunction();
			var obj80 = new MiruClothArrayPage();
			obj80.linkFunction();
			var obj81 = new MiruDungeon();
			obj81.linkFunction();
			var obj82 = new MiruTempCommon();
			obj82.linkFunction();
			var obj83 = new MiruFriend();
			obj83.linkFunction();
			var obj84 = new MiruSubPage();
			obj84.linkFunction();
			var obj85 = new MiruGameNotice();
			obj85.linkFunction();
			var obj86 = new MiruNewYearAct();
			obj86.linkFunction();
			var obj87 = new MiruRebelArmy();
			obj87.linkFunction();
			var obj88 = new MiruRecycle();
			obj88.linkFunction();
			var obj89 = new MiruReddot();
			obj89.linkFunction();
			var obj90 = new MiruRunningMan();
			obj90.linkFunction();
			var obj91 = new MiruSevenDayActivityPage();
			obj91.linkFunction();
			var obj92 = new MiruShopPage();
			obj92.linkFunction();
			var obj93 = new MiruShopStore();
			obj93.linkFunction();
			var obj94 = new MiruTask();
			obj94.linkFunction();
			var obj95 = new MiruOtherItem();
			obj95.linkFunction();
			var obj96 = new MiruTurntable();
			obj96.linkFunction();
			var obj97 = new MiruLoginPage();
			obj97.linkFunction();
			var obj98 = new MiruShowVip();
			obj98.linkFunction();
			var obj99 = new MiruTarining();
			obj99.linkFunction();
			var obj100 = new MiruTreasureManage();
			obj100.linkFunction();
			var obj101 = new MiruTrialTower();
			obj101.linkFunction();
			var obj102 = new MiruUIInterfacePack();
			obj102.linkFunction();
		}
	}
}
